matrix:
    include:
        - language: python
          install:
              - pip install doc8 flake8 Pygments
          script:
              - doc8
              - flake8 examples/
        - language: node_js
          node_js:
              - 10
          script:
              - node_modules/.bin/eslint --ext .html,.js examples/
